services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: testing
      TZ: 'America/New_York'
    volumes:
      - ./container/oracle/initdb.d:/container-entrypoint-initdb.d

  keycloak:
    image: jeffersonlab/keycloak:1.1.1
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8081:8080"
      - "9991:9990"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_HOSTNAME: 'localhost'
      KEYCLOAK_FRONTEND_PORT: '8081'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080'
      KEYCLOAK_HOME: '/opt/keycloak'
      KEYCLOAK_REALM: 'test-realm'
      KEYCLOAK_RESOURCE: 'btm'
      KEYCLOAK_SECRET: 'yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB'
      TZ: 'America/New_York'
    volumes:
      - ./container/keycloak/initdb.d:/container-entrypoint-initdb.d

  puppet:
    image: slominskir/puppet-show:2.1.1
    hostname: puppet
    container_name: puppet
    ports:
      - "3000:3000"
    privileged: true
    environment:
      TZ: 'America/New_York'

  mailhog:
    image: mailhog/mailhog:v1.0.1
    hostname: mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      TZ: 'America/New_York'

  softioc:
    image: jeffersonlab/softioc:1.1.0
    tty: true
    stdin_open: true
    hostname: softioc
    container_name: softioc
    ports:
      - "5065:5065/tcp"
      - "5064:5064/tcp"
      - "5065:5065/udp"
      - "5064:5064/udp"
    volumes:
      - ./container/softioc/db:/db
    entrypoint: "/db/init.sh"
    environment:
      TZ: 'America/New_York'