alter session set container = XEPDB1;

CREATE TABLE BTM_OWNER.MONTHLY_SCHEDULE
(
    MONTHLY_SCHEDULE_ID INTEGER      NOT NULL,
    START_DAY           TIMESTAMP(0) NOT NULL,
    VERSION             INTEGER      NOT NULL,
    PUBLISHED_DATE      DATE         NULL,
    CONSTRAINT MONTHLY_SCHEDULE_PK PRIMARY KEY (MONTHLY_SCHEDULE_ID),
    CONSTRAINT MONTHLY_SCHEDULE_AK1 UNIQUE (START_DAY, VERSION),
    CONSTRAINT MONTHLY_SCHEDULE_CK1 CHECK (EXTRACT(DAY FROM START_DAY) = 1 and EXTRACT(HOUR FROM START_DAY) = 0 and
                                           EXTRACT(MINUTE FROM START_DAY) = 0 AND
                                           EXTRACT(SECOND FROM START_DAY) = 0)
);

CREATE TABLE BTM_OWNER.SCHEDULE_DAY
(
    SCHEDULE_DAY_ID     INTEGER                NOT NULL,
    DAY_MONTH_YEAR      DATE                   NOT NULL,
    MONTHLY_SCHEDULE_ID INTEGER                NOT NULL,
    ACC_PROGRAM         VARCHAR2(24 CHAR)      NOT NULL,
    KILO_VOLTS_PER_PASS INTEGER                NULL,
    NOTE                VARCHAR2(256 CHAR)     NULL,
    HALL_A_PROGRAM_ID   INTEGER                NOT NULL,
    HALL_A_NANO_AMPS    INTEGER                NULL,
    HALL_A_KILO_VOLTS   INTEGER                NULL,
    HALL_A_PASSES       INTEGER                NULL,
    HALL_A_PRIORITY     INTEGER                NULL,
    HALL_A_POLARIZED    CHAR(1 BYTE) DEFAULT 1 NOT NULL,
    HALL_B_PROGRAM_ID   INTEGER                NOT NULL,
    HALL_B_NANO_AMPS    INTEGER                NULL,
    HALL_B_KILO_VOLTS   INTEGER                NULL,
    HALL_B_PASSES       INTEGER                NULL,
    HALL_B_PRIORITY     INTEGER                NULL,
    HALL_B_POLARIZED    CHAR(1 BYTE) DEFAULT 1 NOT NULL,
    HALL_C_PROGRAM_ID   INTEGER                NULL,
    HALL_C_NANO_AMPS    INTEGER                NULL,
    HALL_C_KILO_VOLTS   INTEGER                NULL,
    HALL_C_PASSES       INTEGER                NULL,
    HALL_C_PRIORITY     INTEGER                NULL,
    HALL_C_POLARIZED    CHAR(1 BYTE) DEFAULT 1 NOT NULL,
    HALL_D_PROGRAM_ID   INTEGER                NULL,
    HALL_D_NANO_AMPS    INTEGER                NULL,
    HALL_D_KILO_VOLTS   INTEGER                NULL,
    HALL_D_PASSES       INTEGER                NULL,
    HALL_D_PRIORITY     INTEGER                NULL,
    HALL_D_POLARIZED    CHAR(1 BYTE) DEFAULT 1 NOT NULL,
    HALL_A_NOTE         VARCHAR2(256 CHAR)     NULL,
    HALL_B_NOTE         VARCHAR2(256 CHAR)     NULL,
    HALL_C_NOTE         VARCHAR2(256 CHAR)     NULL,
    HALL_D_NOTE         VARCHAR2(256 CHAR)     NULL,
    MIN_HALL_COUNT      INTEGER                NULL,
    CONSTRAINT SCHEDULE_DAY_PK PRIMARY KEY (SCHEDULE_DAY_ID),
    CONSTRAINT SCHEDULE_DAY_AK1 UNIQUE (DAY_MONTH_YEAR, MONTHLY_SCHEDULE_ID),
    CONSTRAINT SCHEDULE_DAY_FK1 FOREIGN KEY (MONTHLY_SCHEDULE_ID) REFERENCES BTM_OWNER.MONTHLY_SCHEDULE (MONTHLY_SCHEDULE_ID) ON DELETE CASCADE,
    CONSTRAINT SCHEDULE_DAY_CK1 CHECK (DAY_MONTH_YEAR = TRUNC(DAY_MONTH_YEAR)),
    CONSTRAINT SCHEDULE_DAY_CK2 CHECK (ACC_PROGRAM IN ('PHYSICS', 'STUDIES', 'RESTORE', 'ACC', 'DOWN', 'OFF', 'TBD', 'FACDEV')),
    CONSTRAINT SCHEDULE_DAY_CK3 CHECK (HALL_A_POLARIZED IN (0, 1)),
    CONSTRAINT SCHEDULE_DAY_CK4 CHECK (HALL_B_POLARIZED IN (0, 1)),
    CONSTRAINT SCHEDULE_DAY_CK5 CHECK (HALL_C_POLARIZED IN (0, 1)),
    CONSTRAINT SCHEDULE_DAY_CK6 CHECK (HALL_D_POLARIZED IN (0, 1))
);

CREATE TABLE BTM_OWNER.OP_SIGNATURE
(
    OP_SIGNATURE_ID    INTEGER                           NOT NULL,
    START_DAY_AND_HOUR TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL,
    SIGNED_BY          INTEGER                           NOT NULL,
    SIGNED_ROLE        VARCHAR2(20 CHAR)                 NOT NULL,
    SIGNED_DATE        DATE                              NOT NULL,
    CONSTRAINT OP_SIGNATURE_PK PRIMARY KEY (OP_SIGNATURE_ID),
    CONSTRAINT OP_SIGNATURE_AK1 UNIQUE (START_DAY_AND_HOUR, SIGNED_BY, SIGNED_ROLE),
    CONSTRAINT OP_SIGNATURE_CK1 CHECK (EXTRACT(HOUR FROM START_DAY_AND_HOUR) in (23, 7, 15) AND
                                       EXTRACT(MINUTE FROM START_DAY_AND_HOUR) = 0 AND
                                       EXTRACT(SECOND FROM START_DAY_AND_HOUR) = 0),
    CONSTRAINT OP_SIGNATURE_CK2 CHECK (SIGNED_ROLE IN ('CREW_CHIEF', 'OPERABILITY_MANAGER'))
);

CREATE TABLE BTM_OWNER.OP_SHIFT
(
    OP_SHIFT_ID        NUMBER(38, 0)                     NOT NULL,
    START_DAY_AND_HOUR TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL,
    CREW_CHIEF         VARCHAR2(64 CHAR)                 NULL,
    OPERATORS          VARCHAR2(256 CHAR)                NULL,
    REMARK             VARCHAR2(2048 CHAR)               NULL,
    PROGRAM            VARCHAR2(64 CHAR)                 NULL,
    PROGRAM_DEPUTY     VARCHAR2(64 CHAR)                 NULL,
    CONSTRAINT OP_SHIFT_PK PRIMARY KEY (OP_SHIFT_ID),
    CONSTRAINT OP_SHIFT_AK1 UNIQUE (START_DAY_AND_HOUR),
    CONSTRAINT OP_SHIFT_CK1 CHECK (EXTRACT(HOUR FROM START_DAY_AND_HOUR) in (23, 7, 15) AND
                                   EXTRACT(MINUTE FROM START_DAY_AND_HOUR) = 0 AND
                                   EXTRACT(SECOND FROM START_DAY_AND_HOUR) = 0)
);

CREATE TABLE BTM_OWNER.OP_MULTIPLICITY_HOUR
(
    OP_MULTIPLICITY_HOUR_ID NUMBER(38, 0)                     NOT NULL,
    DAY_AND_HOUR            TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL,
    ONE_HALL_UP_SECONDS     NUMBER(4, 0) DEFAULT 0            NOT NULL,
    TWO_HALL_UP_SECONDS     NUMBER(4, 0) DEFAULT 0            NOT NULL,
    THREE_HALL_UP_SECONDS   NUMBER(4, 0) DEFAULT 0            NOT NULL,
    ANY_HALL_UP_SECONDS     NUMBER(4, 0) DEFAULT 0            NOT NULL,
    ALL_HALL_UP_SECONDS     NUMBER(4, 0) DEFAULT 0            NOT NULL,
    DOWN_HARD_SECONDS       NUMBER(4, 0) DEFAULT 0            NOT NULL,
    FOUR_HALL_UP_SECONDS    NUMBER(4, 0) DEFAULT 0            NOT NULL,
    CONSTRAINT OP_MULTIPLICITY_HOUR_PK PRIMARY KEY (OP_MULTIPLICITY_HOUR_ID),
    CONSTRAINT OP_MULTIPLICITY_HOUR_AK1 UNIQUE (DAY_AND_HOUR),
    CONSTRAINT OP_MULTIPLICITY_CK1 CHECK (EXTRACT(MINUTE FROM DAY_AND_HOUR) = 0 AND
                                          EXTRACT(SECOND FROM DAY_AND_HOUR) = 0),
    CONSTRAINT OP_MULTIPLICITY_CK2 CHECK (ONE_HALL_UP_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_MULTIPLICITY_CK3 CHECK (TWO_HALL_UP_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_MULTIPLICITY_CK4 CHECK (THREE_HALL_UP_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_MULTIPLICITY_CK5 CHECK (ANY_HALL_UP_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_MULTIPLICITY_CK6 CHECK (ALL_HALL_UP_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_MULTIPLICITY_CK7 CHECK (DOWN_HARD_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_MULTIPLICITY_CK8 CHECK (FOUR_HALL_UP_SECONDS BETWEEN 0 AND 3600)
);

CREATE TABLE BTM_OWNER.OP_HALL_HOUR
(
    OP_HALL_HOUR_ID NUMBER(38, 0)                     NOT NULL,
    DAY_AND_HOUR    TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL,
    HALL            CHAR(1 CHAR)                      NOT NULL,
    UP_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    TUNE_SECONDS    NUMBER(4, 0) DEFAULT 0            NOT NULL,
    BNR_SECONDS     NUMBER(4, 0) DEFAULT 0            NOT NULL,
    DOWN_SECONDS    NUMBER(4, 0) DEFAULT 0            NOT NULL,
    OFF_SECONDS     NUMBER(4, 0) DEFAULT 0            NOT NULL,
    CONSTRAINT OP_HALL_HOUR_PK PRIMARY KEY (OP_HALL_HOUR_ID),
    CONSTRAINT OP_HALL_HOUR_AK1 UNIQUE (HALL, DAY_AND_HOUR),
    CONSTRAINT OP_HALL_HOUR_CK8 CHECK ( UP_SECONDS + TUNE_SECONDS + BNR_SECONDS + DOWN_SECONDS + OFF_SECONDS = 3600 ),
    CONSTRAINT OP_HALL_HOUR_CK1 CHECK (EXTRACT(MINUTE FROM DAY_AND_HOUR) = 0 AND
                                       EXTRACT(SECOND FROM DAY_AND_HOUR) = 0),
    CONSTRAINT OP_HALL_HOUR_CK2 CHECK (HALL IN ('A', 'B', 'C', 'D')),
    CONSTRAINT OP_HALL_HOUR_CK3 CHECK (UP_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_HALL_HOUR_CK4 CHECK (TUNE_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_HALL_HOUR_CK5 CHECK (BNR_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_HALL_HOUR_CK6 CHECK (DOWN_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_HALL_HOUR_CK7 CHECK (OFF_SECONDS BETWEEN 0 AND 3600)
);

CREATE TABLE BTM_OWNER.OP_CROSS_CHECK_COMMENT
(
    OP_CHECK_COMMENT_ID INTEGER                           NOT NULL,
    START_DAY_AND_HOUR  TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL,
    REMARK              VARCHAR2(2048 CHAR)               NULL,
    REVIEWER_REMARK     VARCHAR2(2048 CHAR)               NULL,
    CONSTRAINT OP_CROSS_CHECK_COMMENT_PK PRIMARY KEY (OP_CHECK_COMMENT_ID),
    CONSTRAINT OP_CROSS_CHECK_COMMENT_AK1 UNIQUE (START_DAY_AND_HOUR)
);

CREATE TABLE BTM_OWNER.OP_ACC_HOUR
(
    OP_ACC_HOUR_ID  INTEGER                           NOT NULL,
    DAY_AND_HOUR    TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL,
    UP_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    SAD_SECONDS     NUMBER(4, 0) DEFAULT 0            NOT NULL,
    DOWN_SECONDS    NUMBER(4, 0) DEFAULT 0            NOT NULL,
    STUDIES_SECONDS NUMBER(4, 0) DEFAULT 0            NOT NULL,
    ACC_SECONDS     NUMBER(4, 0) DEFAULT 0            NOT NULL,
    RESTORE_SECONDS NUMBER(4, 0) DEFAULT 0            NOT NULL,
    CONSTRAINT OP_ACC_HOUR_PK PRIMARY KEY (OP_ACC_HOUR_ID),
    CONSTRAINT OP_ACC_HOUR_AK1 UNIQUE (DAY_AND_HOUR),
    CONSTRAINT OP_ACC_HOUR_CK1 CHECK (EXTRACT(MINUTE FROM DAY_AND_HOUR) = 0 AND
                                      EXTRACT(SECOND FROM DAY_AND_HOUR) = 0),
    CONSTRAINT OP_ACC_HOUR_CK2 CHECK (UP_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_ACC_HOUR_CK3 CHECK (SAD_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_ACC_HOUR_CK4 CHECK (DOWN_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_ACC_HOUR_CK5 CHECK (STUDIES_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_ACC_HOUR_CK6 CHECK (ACC_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_ACC_HOUR_CK7 CHECK (RESTORE_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT OP_ACC_HOUR_CK8 CHECK (
                UP_SECONDS + SAD_SECONDS + DOWN_SECONDS + STUDIES_SECONDS + RESTORE_SECONDS + ACC_SECONDS = 3600 )
);

CREATE TABLE BTM_OWNER.REVISION_INFO
(
    REV      NUMBER(38, 0) NOT NULL,
    REVTSTMP NUMBER(19, 0) NOT NULL,
    USERNAME VARCHAR2(64)  NULL,
    ADDRESS  VARCHAR2(64)  NULL,
    CONSTRAINT REVISION_INFO_PK PRIMARY KEY (REV)
);

CREATE TABLE BTM_OWNER.EXP_HALL_SIGNATURE_AUD
(
    EXP_HALL_SIGNATURE_ID NUMBER(38, 0) NOT NULL,
    REV                   NUMBER(38, 0) NOT NULL,
    REVTYPE               NUMBER(3, 0)  NULL,
    HALL                  CHAR(1)       NOT NULL
        CONSTRAINT VALID_HALL_1014052681 CHECK (HALL IN ('A', 'B', 'C', 'D')),
    START_DAY_AND_HOUR    TIMESTAMP     NOT NULL
        CONSTRAINT VALIDATE_ON_HOUR_873101454 CHECK (EXTRACT(MINUTE FROM START_DAY_AND_HOUR) = 0 AND
                                                     EXTRACT(SECOND FROM START_DAY_AND_HOUR) = 0),
    SIGNED_BY             NUMBER(10, 0) NOT NULL,
    SIGNED_ROLE           VARCHAR2(20)  NOT NULL,
    SIGNED_DATE           DATE          NOT NULL,
    CONSTRAINT EXP_HALL_SIGNATURE_AUD_PK PRIMARY KEY (EXP_HALL_SIGNATURE_ID),
    CONSTRAINT EXP_HALL_SIGNATURE_AUD_FK1 FOREIGN KEY (REV) REFERENCES BTM_OWNER.REVISION_INFO (REV) ON DELETE SET NULL
);

CREATE TABLE BTM_OWNER.EXP_HALL_SIGNATURE
(
    EXP_HALL_SIGNATURE_ID NUMBER(38, 0)                     NOT NULL,
    HALL                  CHAR(1)                           NOT NULL,
    START_DAY_AND_HOUR    TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL,
    SIGNED_BY             NUMBER(10, 0)                     NOT NULL,
    SIGNED_ROLE           VARCHAR2(20)                      NOT NULL,
    SIGNED_DATE           DATE                              NOT NULL,
    CONSTRAINT EXP_HALL_SIGNATURE_PK PRIMARY KEY (EXP_HALL_SIGNATURE_ID),
    CONSTRAINT EXP_HALL_SIGNATURE_AK1 UNIQUE (HALL, START_DAY_AND_HOUR, SIGNED_BY),
    CONSTRAINT EXP_HALL_SIGNATURE_AK2 UNIQUE (HALL, START_DAY_AND_HOUR, SIGNED_ROLE),
    CONSTRAINT VALID_HALL_1850370422 CHECK (HALL IN ('A', 'B', 'C', 'D'))
);

CREATE TABLE BTM_OWNER.EXP_HALL_SHIFT_AUD
(
    EXP_HALL_SHIFT_ID  NUMBER(38, 0)                     NOT NULL,
    REV                NUMBER(38, 0)                     NULL,
    REVTYPE            NUMBER(3, 0)                      NULL,
    HALL               CHAR(1)                           NOT NULL,
    START_DAY_AND_HOUR TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL,
    PURPOSE_ID         NUMBER(38, 0)                     NULL,
    LEADER             VARCHAR2(64)                      NULL,
    WORKERS            VARCHAR2(20)                      NULL,
    REMARK             VARCHAR2(2048)                    NULL,
    CONSTRAINT EXP_HALL_SHIFT_AUD_PK PRIMARY KEY (EXP_HALL_SHIFT_ID),
    CONSTRAINT EXP_HALL_SHIFT_AUD_FK1 FOREIGN KEY (REV) REFERENCES BTM_OWNER.REVISION_INFO (REV) ON DELETE SET NULL,
    CONSTRAINT EXP_HALL_SHIFT_AUD_CK1 CHECK (HALL IN ('A', 'B', 'C', 'D')),
    CONSTRAINT EXP_HALL_SHIFT_AUD_CH2 CHECK (EXTRACT(MINUTE FROM START_DAY_AND_HOUR) = 0 AND
                                             EXTRACT(SECOND FROM START_DAY_AND_HOUR) = 0)
);

CREATE TABLE BTM_OWNER.EXP_HALL_SHIFT_PURPOSE
(
    EXP_HALL_SHIFT_PURPOSE_ID NUMBER(38, 0)      NOT NULL,
    HALL                      CHAR(1 CHAR)       NOT NULL,
    NAME                      VARCHAR2(64)       NOT NULL,
    EXPERIMENT                CHAR(1)            NOT NULL,
    ACTIVE                    CHAR(1) DEFAULT 1  NOT NULL,
    ALIAS                     VARCHAR2(64)       NULL,
    URL                       VARCHAR2(512 CHAR) NULL,
    CONSTRAINT EXP_HALL_SHIFT_PURPOSE_PK PRIMARY KEY (EXP_HALL_SHIFT_PURPOSE_ID),
    CONSTRAINT EXP_HALL_SHIFT_PURPOSE_AK1 UNIQUE (HALL, NAME),
    CONSTRAINT EXP_HALL_SHIFT_PURPOSE_AK2 UNIQUE (HALL, EXP_HALL_SHIFT_PURPOSE_ID),
    CONSTRAINT EXP_HALL_SHIFT_PURPOSE_CK1 CHECK (HALL IN ('A', 'B', 'C', 'D')),
    CONSTRAINT EXP_HALL_SHIFT_PURPOSE_CK2 CHECK (EXPERIMENT IN (0, 1)),
    CONSTRAINT EXP_HALL_SHIFT_PURPOSE_CK3 CHECK (ACTIVE IN (0, 1))
);

CREATE TABLE BTM_OWNER.EXP_HALL_SHIFT
(
    EXP_HALL_SHIFT_ID  NUMBER(38, 0)  NOT NULL,
    HALL               CHAR(1 CHAR)   NOT NULL,
    START_DAY_AND_HOUR TIMESTAMP(0)   NOT NULL,
    PURPOSE_ID         NUMBER(38, 0)  NOT NULL,
    LEADER             VARCHAR2(64)   NULL,
    WORKERS            VARCHAR2(256)  NULL,
    REMARK             VARCHAR2(2048) NULL,
    CONSTRAINT EXP_HALL_SHIFT_PK PRIMARY KEY (EXP_HALL_SHIFT_ID),
    CONSTRAINT EXP_HALL_SHIFT_AK1 UNIQUE (HALL, START_DAY_AND_HOUR),
    CONSTRAINT EXP_HALL_SHIFT_FK1 FOREIGN KEY (HALL, PURPOSE_ID) REFERENCES BTM_OWNER.EXP_HALL_SHIFT_PURPOSE (HALL, EXP_HALL_SHIFT_PURPOSE_ID),
    CONSTRAINT EXP_HALL_SHIFT_CK1 CHECK (HALL IN ('A', 'B', 'C', 'D')),
    CONSTRAINT EXP_HALL_SHIFT_CK2 CHECK (EXTRACT(HOUR FROM START_DAY_AND_HOUR) in (0, 8, 16) AND
                                         EXTRACT(MINUTE FROM START_DAY_AND_HOUR) = 0 AND
                                         EXTRACT(SECOND FROM START_DAY_AND_HOUR) = 0)
);

CREATE TABLE BTM_OWNER.EXP_HALL_HOUR_REASON_TIME_AUD
(
    EXP_HALL_HOUR_REASON_TIME_ID NUMBER(38, 0)          NOT NULL,
    REV                          NUMBER(38, 0)          NULL,
    REVTYPE                      NUMBER(3, 0)           NOT NULL,
    HALL                         CHAR(1)                NOT NULL,
    SECONDS                      NUMBER(4, 0) DEFAULT 0 NOT NULL,
    HOUR_ID                      NUMBER(38, 0)          NULL,
    REASON_ID                    NUMBER(38, 0)          NULL,
    CONSTRAINT EXP_HALL_HOUR_REASON_TIME_AUD_PK PRIMARY KEY (EXP_HALL_HOUR_REASON_TIME_ID),
    CONSTRAINT EXP_HALL_HOUR_REASON_TIME_AUD_FK1 FOREIGN KEY (REV) REFERENCES BTM_OWNER.REVISION_INFO (REV) ON DELETE SET NULL,
    CONSTRAINT EXP_HALL_HOUR_REASON_TIME_AUD_CK1 CHECK (HALL IN ('A', 'B', 'C', 'D')),
    CONSTRAINT EXP_HALL_HOUR_REASON_TIME_AUD_CK2 CHECK (SECONDS BETWEEN 0 AND 3600)
);

CREATE TABLE BTM_OWNER.EXP_HALL_REASON
(
    EXP_HALL_REASON_ID NUMBER(38, 0)     NOT NULL,
    HALL               CHAR(1 CHAR)      NOT NULL,
    NAME               VARCHAR2(64)      NOT NULL,
    ACTIVE             CHAR(1) DEFAULT 1 NOT NULL,
    CONSTRAINT EXP_HALL_REASON_PK PRIMARY KEY (EXP_HALL_REASON_ID),
    CONSTRAINT EXP_HALL_REASON_AK1 UNIQUE (HALL, NAME),
    CONSTRAINT EXP_HALL_REASON_CK1 CHECK (HALL IN ('A', 'B', 'C', 'D')),
    CONSTRAINT EXP_HALL_REASON_CK2 CHECK (ACTIVE IN (0, 1))
);

CREATE TABLE BTM_OWNER.EXP_HALL_HOUR
(
    EXP_HALL_HOUR_ID NUMBER(38, 0)                     NOT NULL,
    HALL             CHAR(1)                           NOT NULL,
    DAY_AND_HOUR     TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL,
    ABU_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    BANU_SECONDS     NUMBER(4, 0) DEFAULT 0            NOT NULL,
    BNA_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    ACC_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    ER_SECONDS       NUMBER(4, 0) DEFAULT 0            NOT NULL,
    PCC_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    UED_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    SCHED_SECONDS    NUMBER(4, 0) DEFAULT 0            NOT NULL,
    STUDIES_SECONDS  NUMBER(4, 0) DEFAULT 0            NOT NULL,
    OFF_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    REMARK           VARCHAR2(2048 CHAR)               NULL,
    CONSTRAINT EXP_HALL_HOUR_PK PRIMARY KEY (EXP_HALL_HOUR_ID),
    CONSTRAINT EXP_HALL_HOUR_AK1 UNIQUE (HALL, DAY_AND_HOUR),
    CONSTRAINT EXP_HALL_HOUR_AK2 UNIQUE (HALL, EXP_HALL_HOUR_ID),
    CONSTRAINT EXP_HALL_HOUR_CK1 CHECK (HALL IN ('A', 'B', 'C', 'D')),
    CONSTRAINT EXP_HALL_HOUR_CK2 CHECK (EXTRACT(MINUTE FROM DAY_AND_HOUR) = 0 AND
                                        EXTRACT(SECOND FROM DAY_AND_HOUR) = 0),
    CONSTRAINT EXP_HALL_HOUR_CK3 CHECK (ABU_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_CK4 CHECK (BANU_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_CK5 CHECK (BNA_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_CK6 CHECK (ACC_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_CK7 CHECK (ER_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_CK8 CHECK (PCC_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_CK9 CHECK (UED_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_CK10 CHECK (SCHED_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_CK11 CHECK (STUDIES_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_CK12 CHECK (OFF_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_CK13 CHECK ( abu_seconds + banu_seconds + bna_seconds + acc_seconds + off_seconds = 3600 ),
    CONSTRAINT EXP_HALL_HOUR_CK14 CHECK ( er_seconds + pcc_seconds + ued_seconds + off_seconds = 3600 )
);

CREATE TABLE BTM_OWNER.EXP_HALL_HOUR_REASON_TIME
(
    EXP_HALL_HOUR_REASON_TIME_ID NUMBER(38, 0)          NOT NULL,
    HALL                         CHAR(1 CHAR)           NOT NULL,
    EXP_HALL_HOUR_ID             NUMBER(38, 0)          NULL,
    REASON                       VARCHAR2(64)           NOT NULL,
    SECONDS                      NUMBER(4, 0) DEFAULT 0 NOT NULL,
    CONSTRAINT EXP_HALL_HOUR_REASON_TIME_PK PRIMARY KEY (EXP_HALL_HOUR_REASON_TIME_ID),
    CONSTRAINT EXP_HALL_HOUR_REASON_TIME_AK1 UNIQUE (HALL, REASON, EXP_HALL_HOUR_ID),
    CONSTRAINT EXP_HALL_HOUR_REASON_TIME_FK1 FOREIGN KEY (HALL, EXP_HALL_HOUR_ID) REFERENCES BTM_OWNER.EXP_HALL_HOUR (HALL, EXP_HALL_HOUR_ID) ON DELETE SET NULL,
    CONSTRAINT EXP_HALL_HOUR_REASON_TIME_FK2 FOREIGN KEY (HALL, REASON) REFERENCES BTM_OWNER.EXP_HALL_REASON (HALL, NAME) ON DELETE CASCADE,
    CONSTRAINT EXP_HALL_HOUR_REASON_TIME_CK1 CHECK (HALL IN ('A', 'B', 'C', 'D')),
    CONSTRAINT EXP_HALL_HOUR_REASON_TIME_CK2 CHECK (SECONDS BETWEEN 0 AND 3600)
);

CREATE TABLE BTM_OWNER.EXP_HALL_HOUR_AUD
(
    EXP_HALL_HOUR_ID NUMBER(38, 0)                     NOT NULL,
    REV              NUMBER(38, 0)                     NULL,
    REVTYPE          NUMBER(3, 0)                      NOT NULL,
    HALL             CHAR(1)                           NOT NULL,
    DAY_AND_HOUR     TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL,
    ABU_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    BANU_SECONDS     NUMBER(4, 0) DEFAULT 0            NOT NULL,
    BNA_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    ACC_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    ER_SECONDS       NUMBER(4, 0) DEFAULT 0            NOT NULL,
    PCC_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    UED_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    SCHED_SECONDS    NUMBER(4, 0) DEFAULT 0            NOT NULL,
    STUDIES_SECONDS  NUMBER(4, 0) DEFAULT 0            NOT NULL,
    OFF_SECONDS      NUMBER(4, 0) DEFAULT 0            NOT NULL,
    REMARK           VARCHAR2(2048)                    NULL,
    CONSTRAINT EXP_HALL_HOUR_AUD_PK PRIMARY KEY (EXP_HALL_HOUR_ID),
    CONSTRAINT EXP_HALL_HOUR_AUD_FK1 FOREIGN KEY (REV) REFERENCES BTM_OWNER.REVISION_INFO (REV) ON DELETE SET NULL,
    CONSTRAINT EXP_HALL_HOUR_AUD_CK1 CHECK (HALL IN ('A', 'B', 'C', 'D')),
    CONSTRAINT EXP_HALL_HOUR_AUD_CK2 CHECK (EXTRACT(MINUTE FROM DAY_AND_HOUR) = 0 AND
                                            EXTRACT(SECOND FROM DAY_AND_HOUR) = 0),
    CONSTRAINT EXP_HALL_HOUR_AUD_CK3 CHECK (ABU_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_AUD_CK4 CHECK (BANU_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_AUD_CK5 CHECK (BNA_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_AUD_CK6 CHECK (ACC_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_AUD_CK7 CHECK (ER_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_AUD_CK8 CHECK (PCC_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_AUD_CK9 CHECK (UED_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_AUD_CK10 CHECK (SCHED_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_AUD_CK11 CHECK (STUDIES_SECONDS BETWEEN 0 AND 3600),
    CONSTRAINT EXP_HALL_HOUR_AUD_CK12 CHECK (OFF_SECONDS BETWEEN 0 AND 3600)
);

CREATE TABLE BTM_OWNER.EXP_HALL_EMAIL_RECIPIENT
(
    EXP_HALL_EMAIL_RECIPIENT_ID NUMBER(38, 0) NOT NULL,
    HALL                        CHAR(1)       NOT NULL,
    EMAIL                       VARCHAR2(256) NOT NULL,
    CONSTRAINT EXP_HALL_EMAIL_RECIPIENT_PK PRIMARY KEY (EXP_HALL_EMAIL_RECIPIENT_ID),
    CONSTRAINT EXP_HALL_EMAIL_RECIPIENT_AK1 UNIQUE (HALL, EMAIL),
    CONSTRAINT EXP_HALL_EMAIL_RECIPIENT_CK1 CHECK (HALL IN ('A', 'B', 'C', 'D'))
);